Repository opengisch/QFieldCloud, pull requests merged in 2022-01, with the labels that each got.

#214 Update .env.example to fix 'invalid sslmode value'
  .env.example
Labels: bug, good first issue, patch

#215 Fix docker-compose.override.local.yml Syntax Error
  docker-compose.override.local.yml
Labels: bug, patch

#213 Improvements on the job execution inside the QGIS container
  docker-app/qfieldcloud/core/serializers.py
  docker-app/qfieldcloud/core/tests/test_delta.py
  docker-app/qfieldcloud/core/tests/test_qfield_file.py
  docker-app/qfieldcloud/core/views/package_views.py
  docker-app/qfieldcloud/core/views/qfield_files_views.py
  docker-app/worker_wrapper/wrapper.py
  docker-qgis/entrypoint.py
  docker-qgis/utils.py
Labels: enhancement, minor

#212 Make gunicorn using multiple workers and multiple threads
  .env.example
  docker-compose.yml
Labels: enhancement, minor

#218 Download files using nginx x-accel-redirect, so the s3 redirect happens withing nginx
  README.md
  conf/nginx/templates/default.conf.template
  docker-app/qfieldcloud/core/tests/test_delta.py
  docker-app/qfieldcloud/core/views/files_views.py
  docker-compose.override.local.yml
  docker-compose.yml
Labels: enhancement, minor

#219 Safer way to export variable from a .env file
  .env.example
  .github/workflows/test.yml
  scripts/init_letsencrypt.sh
Labels: bug, patch

#226 Add status key in the project response
  docker-app/qfieldcloud/core/serializers.py
Labels: enhancement, minor, feedback

#227 Increase timeouts when uploading huge files
  conf/nginx/templates/default.conf.template
Labels: bug, patch

#228 Ignore newcoming deltas with the same id
  docker-app/qfieldcloud/core/exceptions.py
  docker-app/qfieldcloud/core/tests/test_delta.py
  docker-app/qfieldcloud/core/views/deltas_views.py
Labels: enhancement, minor

#231 Fix migrations on deltas for 3d geometry
  docker-app/qfieldcloud/core/migrations/0051_auto_20211125_0444.py
Labels: bug, minor

#232 Fix migrations on deltas for nan coordinates in the geometry
  docker-app/qfieldcloud/core/migrations/0051_auto_20211125_0444.py
Labels: bug
