Repository opengisch/QFieldCloud, pull requests merged in 2022-05, with the labels that each got.

#320 Prepare the list of deltas to be applied on the time of creating the job
  docker-app/qfieldcloud/core/models.py
  docker-app/qfieldcloud/core/tests/test_delta.py
  docker-app/qfieldcloud/core/tests/testdata/delta/deltas/singlelayer_singledelta_project2.json
  docker-app/qfieldcloud/core/utils2/jobs.py
  docker-app/worker_wrapper/wrapper.py
Labels: bug, patch

#297 QF-1839: Use qfieldcloud-sdk to access the files within the worker
  .env.example
  .github/workflows/test.yml
  README.md
  docker-app/Dockerfile
  docker-app/qfieldcloud/authentication/authentication.py
  docker-app/qfieldcloud/authentication/migrations/0002_alter_authtoken_client_type.py
  docker-app/qfieldcloud/authentication/models.py
  docker-app/qfieldcloud/core/management/commands/dequeue.py
  docker-app/qfieldcloud/core/middleware/test.py
  docker-app/qfieldcloud/core/migrations/0053_project_last_package.py
  docker-app/qfieldcloud/core/models.py
  docker-app/qfieldcloud/core/tests/test_delta.py
  docker-app/qfieldcloud/core/tests/test_qgis_file.py
  docker-app/qfieldcloud/core/urls.py
  docker-app/qfieldcloud/core/utils.py
  docker-app/qfieldcloud/core/utils2/__init__.py
  docker-app/qfieldcloud/core/utils2/db.py
  docker-app/qfieldcloud/core/views/files_views.py
  docker-app/qfieldcloud/core/views/package_views.py
  docker-app/qfieldcloud/core/views/qfield_files_views.py
  docker-app/qfieldcloud/settings.py
  docker-app/worker_wrapper/wrapper.py
  docker-compose.override.local.yml
  docker-compose.override.test.yml
  docker-compose.yml
  docker-qgis/Dockerfile
  docker-qgis/apply_deltas.py
  docker-qgis/entrypoint.py
  docker-qgis/process_projectfile.py
  docker-qgis/requirements.txt
  docker-qgis/utils.py
Labels: enhancement, minor

#325 Secrets fine-tuning
  docker-app/qfieldcloud/core/migrations/0052_secret.py
  docker-app/qfieldcloud/core/migrations/0054_auto_20220505_1948.py
  docker-app/qfieldcloud/core/models.py
  docker-app/qfieldcloud/core/permissions_utils.py
  docker-app/qfieldcloud/core/tests/test_packages.py
  docker-app/qfieldcloud/core/tests/testdata/delta/project_pgservice.qgs
  docker-app/worker_wrapper/wrapper.py
Labels: bug, patch

#326 Clean up outdated project packages
  docker-app/qfieldcloud/core/cron.py
  docker-app/qfieldcloud/core/middleware/test.py
  docker-app/qfieldcloud/core/migrations/0055_auto_20220506_1240.py
  docker-app/qfieldcloud/core/utils2/storage.py
  docker-app/qfieldcloud/settings.py
  docker-app/worker_wrapper/wrapper.py
Labels: chore

#330 Added core_user.username UPPER index, as it is mostly compared with
  docker-app/qfieldcloud/core/migrations/0053_auto_20220505_1948.py
  docker-app/qfieldcloud/core/migrations/0054_project_last_package.py
  docker-app/qfieldcloud/core/migrations/0055_auto_20220204_1654.py
  docker-app/qfieldcloud/core/migrations/0055_auto_20220506_1240.py
  docker-app/qfieldcloud/core/models.py
Labels: bug, patch

#331 Added debug toolbar for local development
  docker-app/qfieldcloud/settings.py
  docker-app/qfieldcloud/urls.py
  docker-app/requirements.txt
  docker-compose.override.local.yml
Labels: enhancement, minor, chore

#333 Run cron every 1min and restart ofelia automatically
  docker-compose.yml
Labels: bug, patch

#329 QF-1552: implement function to get number of active users
  docker-app/qfieldcloud/core/models.py
  docker-app/qfieldcloud/core/tests/test_organization.py
Labels: enhancement, minor

#323 QF-1009: disable offline non-geopackages layers for community accounts
  docker-app/qfieldcloud/core/models.py
  docker-app/qfieldcloud/core/views/deltas_views.py
  docker-app/qfieldcloud/subscription/migrations/0002_populate_account_types.py
  docker-app/qfieldcloud/subscription/tests/data/project_pgservice.qgs
  docker-app/qfieldcloud/subscription/tests/data/project_pgservice_delta_1.json
  docker-app/qfieldcloud/subscription/tests/data/project_pgservice_delta_2.json
  docker-app/qfieldcloud/subscription/tests/test_external_db.py
  docker-qgis/apply_deltas.py
Labels: enhancement, minor

#306 Update Port where django is running
  README.md
Labels: chore
