Repository opengisch/QFieldCloud, pull requests merged in 2022-11, with the labels that each got.

#434 Add subscription model
  .env.example
  docker-app/Dockerfile
  docker-app/qfieldcloud/core/admin.py
  docker-app/qfieldcloud/core/exceptions.py
  docker-app/qfieldcloud/core/migrations/0059_auto_20221028_1806.py
  docker-app/qfieldcloud/core/models.py
  docker-app/qfieldcloud/core/permissions_utils.py
  docker-app/qfieldcloud/core/tests/test_permission.py
  docker-app/qfieldcloud/core/tests/test_project.py
  docker-app/qfieldcloud/core/tests/test_qgis_file.py
  docker-app/qfieldcloud/core/tests/test_queryset.py
  docker-app/qfieldcloud/core/tests/utils.py
  docker-app/qfieldcloud/core/utils2/storage.py
  docker-app/qfieldcloud/core/views/files_views.py
  docker-app/qfieldcloud/core/views/projects_views.py
  docker-app/qfieldcloud/settings.py
  docker-app/qfieldcloud/subscription/exceptions.py
  docker-app/qfieldcloud/subscription/migrations/0003_auto_20221028_1901.py
  docker-app/qfieldcloud/subscription/migrations/0004_auto_20220923_1602.py
  docker-app/qfieldcloud/subscription/models.py
  docker-app/qfieldcloud/subscription/sql_config.py
  docker-app/qfieldcloud/subscription/tests/test_organization.py
  docker-app/qfieldcloud/subscription/tests/test_package.py
  docker-app/qfieldcloud/subscription/tests/test_storage_quota.py
  docker-app/qfieldcloud/subscription/tests/test_subscription.py
  docker-app/requirements.txt
  docker-compose.yml
Labels: enhancement, minor

#437 Automatically scale worker_wrapper on startup
  .env.example
  docker-app/qfieldcloud/core/models.py
  docker-app/qfieldcloud/settings.py
  docker-compose.override.dev.yml
  docker-compose.override.local.yml
  docker-compose.override.test.yml
  docker-compose.yml
Labels: enhancement, patch

#440 Organization subscriptions
  .pre-commit-config.yaml
  docker-app/qfieldcloud/core/migrations/0059_auto_20221028_1806.py
  docker-app/qfieldcloud/core/models.py
  docker-app/qfieldcloud/core/permissions_utils.py
  docker-app/qfieldcloud/core/tests/test_organization.py
  docker-app/qfieldcloud/core/tests/utils.py
  docker-app/qfieldcloud/settings.py
  docker-app/qfieldcloud/subscription/migrations/0004_auto_20220923_1602.py
  docker-app/qfieldcloud/subscription/models.py
  docker-app/qfieldcloud/subscription/tests/test_subscription.py
Labels: enhancement, minor

#442 Fix typos `initial_susbscription_status` -> `initial_subscription_status`
  docker-app/qfieldcloud/core/tests/utils.py
  docker-app/qfieldcloud/subscription/migrations/0004_auto_20220923_1602.py
  docker-app/qfieldcloud/subscription/models.py
  docker-app/qfieldcloud/subscription/tests/test_package.py
Labels: bug

#443 Bump qgis to 3.28.2
  docker-qgis/Dockerfile
Labels: enhancement, patch

#446 Cleanup requirements.txt and use multistage build
  docker-app/Dockerfile
  docker-app/requirements.txt
  docker-app/requirements_runtime.txt
  docker-app/requirements_test.txt
  docker-app/requirements_worker_wrapper.txt
  docker-compose.override.test.yml
  docker-compose.yml
Labels: enhancement, minor

#420 qgis: fix empty sourceLayerId
  docker-app/qfieldcloud/core/tests/test_delta.py
  docker-app/qfieldcloud/core/tests/testdata/delta/deltas/singlelayer_singledelta_empty_source_layer_id.json
  docker-qgis/apply_deltas.py
Labels: bug, patch

#447 Bump python:3.10.8-slim-buster, compiled psycopg, no extra deps
  docker-app/Dockerfile
  docker-app/requirements.txt
  docker-app/requirements_test.txt
Labels: enhancement, major

#438 Infrastructure for selenium tests
  .env.example
  conf/nginx/templates/default.conf.template
  docker-app/requirements_test.txt
Labels: enhancement, minor

#449 Bump docker compose versions
  docker-compose.override.dev.yml
  docker-compose.override.local.yml
  docker-compose.override.test.yml
Labels: enhancement, patch
