Repository opengisch/QFieldCloud, pull requests merged in 2022-02, with the labels that each got.

#234 Add limit argument how many users should be invited per run
  docker-app/qfieldcloud/core/management/commands/inviteusers.py
  docker-app/qfieldcloud/settings.py
Labels: enhancement, patch

#237 [Backport release] Add limit argument how many users should be invited per run
  docker-app/qfieldcloud/core/management/commands/inviteusers.py
  docker-app/qfieldcloud/settings.py
Labels: bug, patch

#239 Fix unable to add the owner of an organization to a team
  docker-app/qfieldcloud/core/models.py
Labels: bug, patch

#244 Allow running parallel jobs on the server
  docker-app/qfieldcloud/core/serializers.py
Labels: bug, patch

#242 Fix storage size calculation to include old versions
  docker-app/qfieldcloud/core/models.py
  docker-app/qfieldcloud/core/utils.py
Labels: enhancement, minor

#246 Fix needs_repackaging check, last_packaged < last_updated => need repackaging
  docker-app/qfieldcloud/core/models.py
  docker-app/qfieldcloud/core/tests/test_packages.py
  docker-app/worker_wrapper/wrapper.py
  docker-qgis/utils.py
Labels: bug, patch

#249 Restart nginx automatically and remove circular dependency
  docker-compose.yml
Labels: bug, patch

#241 Purge old versions of project files
  docker-app/qfieldcloud/core/management/commands/purge_old_file_versions.py
  docker-app/qfieldcloud/core/models.py
  docker-app/qfieldcloud/core/tests/test_qgis_file.py
  docker-app/qfieldcloud/core/utils2/storage.py
  docker-app/qfieldcloud/core/views/files_views.py
Labels: enhancement, minor

#251 Added delete_file_version function to deletes a specific file version
  docker-app/qfieldcloud/core/utils.py
  docker-app/qfieldcloud/core/utils2/storage.py
  docker-app/qfieldcloud/core/views/files_views.py
Labels: enhancement, minor

#252 When a file is uploaded to a project, start a new process_projectfile job
  docker-app/qfieldcloud/core/models.py
  docker-app/qfieldcloud/core/utils2/storage.py
  docker-app/qfieldcloud/core/views/files_views.py
Labels: enhancement, minor

#275 No need to have an invitation to register
  docker-app/qfieldcloud/settings.py
Labels: enhancement, minor

#278 Print QGIS version withing the worker and set XDG_RUNTIME_DIR
  docker-qgis/Dockerfile
  docker-qgis/entrypoint.py
  docker-qgis/utils.py
Labels: bug, patch

#279 s3 file links fixes
  docker-app/qfieldcloud/core/serializers.py
  docker-app/qfieldcloud/core/utils2/storage.py
  docker-app/qfieldcloud/core/views/files_views.py
Labels: bug, patch

#282 Fix first_name, last_name etc fields in token serializer
  docker-app/qfieldcloud/core/models.py
  docker-app/qfieldcloud/core/serializers.py
Labels: bug, patch

#281 Block requests by IP, only allow requests with proper host header
  conf/nginx/templates/default.conf.template
  docker-redis/redis.conf
Labels: enhancement, patch
