Repository opengisch/QFieldCloud, pull requests merged in 2023-07, with the labels that each got.

#699 QF-2704 Making sure strings are encoded when sending to Sentry
  docker-app/qfieldcloud/core/tests/test_sentry.py
  docker-app/qfieldcloud/core/utils2/sentry.py
Labels: patch

#709 QF-2838 Public projects are not editable by default
  docker-app/qfieldcloud/core/migrations/0070_alter_project_is_public.py
  docker-app/qfieldcloud/core/models.py
Labels: bug, patch

#705 Fix wrong test in test_organization
  docker-app/qfieldcloud/core/tests/test_organization.py
Labels: patch, chore

#700 Add a rule about commits testability in PRs
  README.md
Labels: documentation

#704 Show active members in the Organization Admin
  docker-app/qfieldcloud/core/admin.py
  docker-app/qfieldcloud/subscription/models.py
Labels: enhancement, minor

#713 Added more logging during job runs
  docker-qgis/entrypoint.py
  docker-qgis/process_projectfile.py
  docker-qgis/utils.py
Labels: enhancement, patch

#710 Paginator for Projects as PoC
  docker-app/qfieldcloud/core/pagination.py
  docker-app/qfieldcloud/core/tests/test_api.py
  docker-app/qfieldcloud/core/views/projects_views.py
Labels: enhancement, minor

#718 Fix email export and add extra columns to the export
  docker-app/qfieldcloud/core/admin.py
Labels: bug, patch, admin

#711 Customize Model-level Pagination
  docker-app/qfieldcloud/core/pagination.py
  docker-app/qfieldcloud/core/tests/test_api.py
  docker-app/qfieldcloud/core/views/projects_views.py
  docker-app/qfieldcloud/settings.py
Labels: enhancement, minor

#717 Qf 2873 Add optional pagination to certain endpoints in the QFieldCloud API
  docker-app/qfieldcloud/core/views/collaborators_views.py
  docker-app/qfieldcloud/core/views/deltas_views.py
  docker-app/qfieldcloud/core/views/jobs_views.py
  docker-app/qfieldcloud/core/views/members_views.py
  docker-app/qfieldcloud/core/views/projects_views.py
  docker-app/qfieldcloud/core/views/users_views.py
  docker-app/qfieldcloud/settings.py
Labels: enhancement, minor

#716 Set final status to jobs that have been killed by docker engine
  docker-app/worker_wrapper/wrapper.py
Labels: bug, patch

#723 Ignore validation errors for sentry
  docker-app/qfieldcloud/settings.py
Labels: patch, chore

#720 QF-2908 swagger docs
  docker-app/qfieldcloud/core/views/collaborators_views.py
  docker-app/qfieldcloud/core/views/deltas_views.py
  docker-app/qfieldcloud/core/views/jobs_views.py
  docker-app/qfieldcloud/core/views/members_views.py
  docker-app/qfieldcloud/core/views/projects_views.py
  docker-app/qfieldcloud/core/views/users_views.py
Labels: chore

#714 Fix misleading comments within the subscription code
  docker-app/qfieldcloud/subscription/models.py
Labels: patch, chore

#721 Skip downloading the S3 metadata if `skip_metadata` is passed to the API `/files/` list endpoint
  docker-app/qfieldcloud/core/tests/test_qgis_file.py
  docker-app/qfieldcloud/core/views/files_views.py
Labels: enhancement, patch

#725 [admin] Be more explicit the numbers mean in storage filed in Person/Org admin
  docker-app/qfieldcloud/core/admin.py
Labels: enhancement, patch, UI/UX, admin

#727 Bump `qfieldcloud-sdk` from `0.6.1` to `0.7.0` to ignore the `sha256` metadata
  docker-qgis/requirements.txt
Labels: enhancement, patch

#728 Docs - Remove old syntax for git clone
  README.md
Labels: documentation, chore

#729 Seems searching for multiple labels do not work
  docker-app/worker_wrapper/wrapper.py
Labels: bug, patch

#726 Added `Project.problems` to list failing requirements for the project file
  docker-app/qfieldcloud/core/models.py
Labels: enhancement, patch

#733 QfcLimitOffsetPagination default limit
  docker-app/qfieldcloud/core/pagination.py
  docker-app/qfieldcloud/core/tests/test_api.py
Labels: patch

#735 Do not check for PK of project layers if not a vector layer
  docker-app/qfieldcloud/core/models.py
Labels: bug, patch

#736 Recreate core_delta_geom_insert_trigger and add delta_geom to admin
  docker-app/qfieldcloud/core/admin.py
  docker-app/qfieldcloud/core/migrations/0071_auto_20230717_2243.py
Labels: bug, patch

#742 Add flake8 rule about walrus operators
  .pre-commit-config.yaml
  docker-qgis/utils.py
Labels: chore

#750 Do not steal the ownership of the project if not explicitly provided
  docker-app/qfieldcloud/core/serializers.py
Labels: bug, patch

#722 Migration drf_yasg (Swagger) -> drf_spectacular (Open API 3)
  docker-app/qfieldcloud/core/pagination.py
  docker-app/qfieldcloud/core/views/collaborators_views.py
  docker-app/qfieldcloud/core/views/deltas_views.py
  docker-app/qfieldcloud/core/views/files_views.py
  docker-app/qfieldcloud/core/views/jobs_views.py
  docker-app/qfieldcloud/core/views/members_views.py
  docker-app/qfieldcloud/core/views/projects_views.py
  docker-app/qfieldcloud/core/views/qfield_files_views.py
  docker-app/qfieldcloud/core/views/status_views.py
  docker-app/qfieldcloud/core/views/users_views.py
  docker-app/qfieldcloud/settings.py
  docker-app/qfieldcloud/urls.py
  docker-app/requirements.txt
Labels: enhancement, chore, do not merge
