Repository opengisch/QFieldCloud, pull requests merged in 2023-04, with the labels that each got.

#611 Qf 2641 code style improvements
  docker-app/qfieldcloud/core/management/commands/dequeue.py
Labels: enhancement

#624 Bump `jinja` from `3.0.3` to `3.1.2`
  docker-app/requirements.txt
Labels: enhancement, patch

#623 Bump a batch of patch versions for dependencies
  docker-app/requirements.txt
Labels: enhancement, patch

#620 Rename subscription qs.active to current
  docker-app/qfieldcloud/subscription/models.py
Labels: refactor

#628 Add `notes` field to plans, packages, packagetypes and subscriptions
  docker-app/qfieldcloud/subscription/migrations/0006_auto_20230426_2222.py
  docker-app/qfieldcloud/subscription/models.py
Labels: enhancement, patch, admin

#629 Speed up jobs admin by removing TOAST-ed columns from the query
  docker-app/qfieldcloud/core/admin.py
Labels: enhancement, patch, admin

#630 Fix migrations with view not having access to a new column
  docker-app/qfieldcloud/subscription/migrations/0006_auto_20230426_2222.py
Labels: bug, patch

#621 No extra order -pk in admin change list
  docker-app/qfieldcloud/core/admin.py
Labels: admin, performance

#634 Fix misleading the HTTP clients to cache package files for 10 minutes
  docker-app/qfieldcloud/core/views/package_views.py
Labels: bug, patch
