Repository opengisch/QFieldCloud, pull requests merged in 2023-02, with the labels that each got.

#485 Setup sentry environment
  docker-compose.yml
Labels: enhancement, patch

#482 Add test that confirms the outdated packages are deleted
  docker-app/qfieldcloud/core/tests/test_packages.py
  docker-app/qfieldcloud/core/utils2/storage.py
Labels: bug, patch

#483 Recalculate project size when soft delete is performed in project files
  docker-app/qfieldcloud/core/utils.py
Labels: bug, patch

#486 Keep more logs
  docker-compose.yml
Labels: enhancement, patch

#484 Added request id in the logging
  conf/nginx/templates/default.conf.template
  docker-app/qfieldcloud/core/logging/formatters.py
  docker-app/qfieldcloud/settings.py
  docker-app/requirements.txt
Labels: enhancement, patch

#487 Rename `remove_` prefixed functions to `delete_`, so we don't use 3 naming conventions
  docker-app/qfieldcloud/core/models.py
  docker-app/qfieldcloud/core/utils2/storage.py
Labels: enhancement, patch

#488 Log warning instead of asserting when trying to delete a file that does not exist
  docker-app/qfieldcloud/core/utils2/storage.py
Labels: bug, patch

#490 Bump django to 3.2.17
  docker-app/requirements.txt
Labels: bug, patch

#491 Make sentry skip some noisy errors
  .env.example
  docker-app/qfieldcloud/settings.py
  docker-compose.yml
Labels: enhancement, patch

#492 Fix all mypy warnings in `utils2/storage.py`
  docker-app/qfieldcloud/core/utils2/storage.py
Labels: bug, patch

#493 Bump few dependencies from JazzBand
  docker-app/requirements.txt
Labels: enhancement, patch

#494 Bump `django-axes` dependency to the latest 5.40.1
  docker-app/qfieldcloud/core/tests/test_admin.py
  docker-app/requirements.txt
Labels: enhancement, patch

#498 Fix configuration of Sentry by converting the envvar SENTRY_SAMPLE_RATE to a float
  docker-app/qfieldcloud/settings.py
Labels: patch

#497 Bump django-audit dependency to the latest 2.2.2
  docker-app/qfieldcloud/core/models.py
  docker-app/qfieldcloud/core/tests/test_admin.py
  docker-app/qfieldcloud/settings.py
  docker-app/requirements.txt
Labels: enhancement, patch

#499 Store the actual total file bytes in the database, instead of estimateded MB
  docker-app/qfieldcloud/core/admin.py
  docker-app/qfieldcloud/core/management/commands/calcprojectstorage.py
  docker-app/qfieldcloud/core/migrations/0060_alter_project_storage_size_mb.py
  docker-app/qfieldcloud/core/models.py
  docker-app/qfieldcloud/core/tests/test_qgis_file.py
  docker-app/qfieldcloud/core/utils.py
  docker-app/qfieldcloud/core/utils2/storage.py
  docker-app/qfieldcloud/core/views/files_views.py
  docker-app/qfieldcloud/settings.py
  scripts/debug.sql
Labels: enhancement, patch

#500 Temporary fix for debug queries by fixing renamed fields and hiding the subscription plan.
  scripts/debug.sql
Labels: bug, chore

#503 Support deleting avatars of users with dashes in the name
  docker-app/qfieldcloud/core/utils2/storage.py
Labels: bug, patch

#502 Slowly transform `_mb` methods to `_bytes`, as it is more precise and less error prone
  docker-app/qfieldcloud/core/models.py
  docker-app/qfieldcloud/core/views/files_views.py
  docker-app/qfieldcloud/core/views/projects_views.py
  docker-app/qfieldcloud/subscription/models.py
Labels: enhancement, patch

#504 Allow also teams as project collaborators when project is within organization
  docker-app/qfieldcloud/core/models.py
  docker-app/qfieldcloud/core/utils2/projects.py
Labels: bug, patch

#505 Speed up QFieldCloud admin by referencing user with autocomplete view
  docker-app/qfieldcloud/core/admin.py
  docker-app/qfieldcloud/core/models.py
Labels: enhancement, patch

#506 Revert "Temporary disable non required deletions"
  docker-app/qfieldcloud/core/tests/test_qgis_file.py
  docker-app/qfieldcloud/core/views/files_views.py
  docker-app/qfieldcloud/settings.py
  docker-app/qfieldcloud/subscription/tests/test_package.py
Labels: bug, patch

#507 Bump QGIS 3.28.3
  docker-qgis/Dockerfile
Labels: enhancement, patch

#508 Allow searching by email in admin in people and organizations
  docker-app/qfieldcloud/core/admin.py
Labels: enhancement, patch

#509 Remove the sample sentry DNS from .env.example
  .env.example
Labels: bug, chore

#510 Opening community projects causes an error because account.user is not an Organization instance
  docker-app/qfieldcloud/subscription/models.py
Labels: bug, patch

#512 Add is_incognito and audit fields to ProjectCollaborator
  docker-app/qfieldcloud/core/admin.py
  docker-app/qfieldcloud/core/migrations/0061_add_incognito_and_audit_to_collaborators.py
  docker-app/qfieldcloud/core/models.py
  docker-app/qfieldcloud/core/sql_config.py
  docker-app/qfieldcloud/core/tests/test_project.py
  docker-app/qfieldcloud/core/utils2/projects.py
Labels: enhancement, patch

#511 Do not account staff users as active users
  docker-app/qfieldcloud/core/models.py
  docker-app/qfieldcloud/core/tests/test_organization.py
Labels: enhancement, patch

#516 Prefer `ForeignKey(User, limit_choice_to=models.Q(type=Person))`
  docker-app/qfieldcloud/core/migrations/0062_auto_20230216_1137.py
  docker-app/qfieldcloud/core/models.py
Labels: bug, patch

#524 Added docs to clearly state the misleading name of `SubscriptionQuerySet.active()`
  docker-app/qfieldcloud/subscription/models.py
Labels: chore

#520 Splitting ci between code checks and tests proper to decrease waiting…
  .github/workflows/test.yml
Labels: chore

#525 Remove the pipenv dependency for envvar validation
  .github/workflows/test.yml
  scripts/check_envvars.sh
Labels: chore

#528 Fix deleting versions with `include_older=True`
  docker-app/qfieldcloud/core/utils2/storage.py
Labels: bug, patch

#530 Do not offer cancelling a subscription is already scheduled to be cancelled
  docker-app/qfieldcloud/core/permissions_utils.py
Labels: bug, patch

#533 Users getting error 500 when trying to register with username taken by an Organization
  docker-app/qfieldcloud/core/adapters.py
Labels: bug, patch

#523 Make sure QFieldCloud is compatible with `nan` coords sent by QField 2.6+
  docker-app/qfieldcloud/core/tests/test_delta.py
  docker-app/qfieldcloud/core/tests/testdata/delta/deltas/multilayer_multidelta.json
  docker-app/qfieldcloud/core/tests/testdata/delta/deltas/multistage_p1_c1_create.json
  docker-app/qfieldcloud/core/tests/testdata/delta/deltas/multistage_p2_c2_create.json
  docker-app/qfieldcloud/core/tests/testdata/delta/deltas/multistage_p3_c1_patch.json
  docker-app/qfieldcloud/core/tests/testdata/delta/deltas/multistage_p4_c2_patch.json
  docker-app/qfieldcloud/core/tests/testdata/delta/deltas/multistage_p5_c1_delete.json
  docker-app/qfieldcloud/core/tests/testdata/delta/deltas/multistage_p6_c2_delete.json
  docker-app/qfieldcloud/core/tests/testdata/delta/deltas/singlelayer_multidelta.json
  docker-app/qfieldcloud/core/tests/testdata/delta/deltas/singlelayer_multidelta_delta_with_xy_for_xyz_layer.json
  docker-app/qfieldcloud/core/tests/testdata/delta/deltas/singlelayer_multidelta_delta_with_xy_for_xyzm_layer.json
  docker-app/qfieldcloud/core/tests/testdata/delta/deltas/singlelayer_multidelta_delta_with_xyz_for_xyz_layer.json
  docker-app/qfieldcloud/core/tests/testdata/delta/deltas/singlelayer_multidelta_delta_with_xyz_for_xyzm_layer.json
  docker-app/qfieldcloud/core/tests/testdata/delta/deltas/singlelayer_multidelta_delta_with_xyz_nan_for_xyz_layer.json
  docker-app/qfieldcloud/core/tests/testdata/delta/deltas/singlelayer_multidelta_delta_with_xyz_nan_for_xyzm_layer.json
  docker-app/qfieldcloud/core/tests/testdata/delta/deltas/singlelayer_multidelta_delta_with_xyzm_for_xyzm_layer.json
  docker-app/qfieldcloud/core/tests/testdata/delta/deltas/singlelayer_multidelta_delta_with_xyzm_nan_for_xyzm_layer.json
  docker-app/qfieldcloud/core/tests/testdata/delta/deltas/singlelayer_multidelta_delta_with_xyzm_nannan_for_xyzm_layer.json
  docker-app/qfieldcloud/core/tests/testdata/delta/deltas/singlelayer_multidelta_patch_create.json
  docker-app/qfieldcloud/core/tests/testdata/delta/deltas/singlelayer_singledelta.json
  docker-app/qfieldcloud/core/tests/testdata/delta/deltas/singlelayer_singledelta2.json
  docker-app/qfieldcloud/core/tests/testdata/delta/deltas/singlelayer_singledelta3.json
  docker-app/qfieldcloud/core/tests/testdata/delta/deltas/singlelayer_singledelta4.json
  docker-app/qfieldcloud/core/tests/testdata/delta/deltas/singlelayer_singledelta5.json
  docker-app/qfieldcloud/core/tests/testdata/delta/deltas/singlelayer_singledelta6.json
  docker-app/qfieldcloud/core/tests/testdata/delta/deltas/singlelayer_singledelta_conflict.json
  docker-app/qfieldcloud/core/tests/testdata/delta/deltas/singlelayer_singledelta_conflict2.json
  docker-app/qfieldcloud/core/tests/testdata/delta/deltas/singlelayer_singledelta_diff_content.json
  docker-app/qfieldcloud/core/tests/testdata/delta/deltas/singlelayer_singledelta_empty_source_layer_id.json
  docker-app/qfieldcloud/core/tests/testdata/delta/deltas/singlelayer_singledelta_null.json
  docker-app/qfieldcloud/core/tests/testdata/delta/deltas/singlelayer_singledelta_project2.json
  docker-app/qfieldcloud/core/tests/testdata/delta/project.qgs
  docker-app/qfieldcloud/core/tests/testdata/delta/testdata.gpkg
  docker-app/requirements_test.txt
  docker-qgis/apply_deltas.py
  docker-qgis/tests/testdata/project2apply/deltas/multilayer_multidelta.json
  docker-qgis/tests/testdata/project2apply/deltas/singlelayer_multidelta.json
  docker-qgis/tests/testdata/project2apply/deltas/singlelayer_singledelta.json
  docker-qgis/tests/testdata/project2apply/project.qgs
Labels: bug, patch

#532 Select related "plan" from the subscription
  docker-app/qfieldcloud/subscription/models.py
Labels: enhancement, patch

#522 QF-2493 export users emails to csv
  docker-app/qfieldcloud/core/admin.py
  docker-app/qfieldcloud/core/templates/admin/account/emailaddress/change_list.html
  docker-app/qfieldcloud/core/tests/test_admin.py
Labels: enhancement, patch

#534 Fix `createuseraccount` script as plans are no longer stored there
  docker-app/qfieldcloud/core/management/commands/createuseraccounts.py
Labels: bug, patch
