Repository opengisch/QFieldCloud, pull requests merged in 2023-06, with the labels that each got.

#678 No subscriptions managed_by AnonymousUser
  docker-app/qfieldcloud/subscription/models.py
Labels: bug, patch

#675 QF-2700 Run makemigrations --check right after building
  .github/workflows/test.yml
  docker-app/qfieldcloud/core/migrations/0009_geodb.py
  docker-app/qfieldcloud/core/models.py
Labels: chore

#682 QF-2711 Adding a few failsafes around ListFilesView.get()
  docker-app/qfieldcloud/core/tests/test_qgis_file.py
  docker-app/qfieldcloud/core/views/files_views.py
Labels: enhancement, minor

#686 Enable Groups model and groups field in People view in Django admin
  docker-app/qfieldcloud/core/admin.py
Labels: enhancement, patch

#676 QF-2507 Configure the number of file versions per project
  docker-app/qfieldcloud/core/migrations/0069_auto_20230616_0827.py
  docker-app/qfieldcloud/core/models.py
  docker-app/qfieldcloud/core/utils2/storage.py
Labels: enhancement, minor

#693 Bump QGIS 3.30.3
  docker-qgis/Dockerfile
Labels: enhancement, patch

#695 QF-2657 Improving tests on CI: parallel build/testing
  .github/workflows/test.yml
Labels: chore

#697 Set dequeue transaction level to repeatable read so we have stable data
  docker-app/qfieldcloud/core/management/commands/dequeue.py
Labels: bug, patch

#698 Ensure connection to the master node as soon as we have the DB session
  docker-app/qfieldcloud/core/management/commands/dequeue.py
Labels: bug, patch

#702 [WIP] Suggest common base methods for active users methods
  docker-app/qfieldcloud/core/models.py
Labels: do not merge

#684 QF-2711 Fine tune error handling in the `files` API endpoint
  docker-app/qfieldcloud/core/utils.py
  docker-app/qfieldcloud/core/views/files_views.py
Labels: patch
