Repository opengisch/QFieldCloud, pull requests merged in 2023-05, with the labels that each got.

#637 Bump qgis version to 3.30.2
  docker-qgis/Dockerfile
Labels: enhancement, patch

#625 Rename active subscription to current, everywhere
  docker-app/qfieldcloud/core/admin.py
  docker-app/qfieldcloud/core/models.py
  docker-app/qfieldcloud/core/permissions_utils.py
  docker-app/qfieldcloud/core/tests/test_permission.py
  docker-app/qfieldcloud/core/tests/utils.py
  docker-app/qfieldcloud/core/utils2/storage.py
  docker-app/qfieldcloud/subscription/models.py
  docker-app/qfieldcloud/subscription/tests/test_organization.py
  docker-app/qfieldcloud/subscription/tests/test_package.py
  docker-app/qfieldcloud/subscription/tests/test_subscription.py
Labels: refactor

#638 Bump various deps
  docker-app/requirements.txt
Labels: enhancement, patch

#622 Reject job and project creation for unsufficient useraccount
  docker-app/qfieldcloud/core/exceptions.py
  docker-app/qfieldcloud/core/models.py
  docker-app/qfieldcloud/core/tests/test_job.py
  docker-app/qfieldcloud/core/tests/test_project.py
  docker-app/qfieldcloud/settings.py
Labels: bug, patch

#639 Qf 2661 move certain exceptions to subscription
  docker-app/qfieldcloud/core/exceptions.py
  docker-app/qfieldcloud/core/models.py
  docker-app/qfieldcloud/core/tests/test_job.py
  docker-app/qfieldcloud/core/tests/test_project.py
  docker-app/qfieldcloud/core/views/files_views.py
  docker-app/qfieldcloud/core/views/projects_views.py
  docker-app/qfieldcloud/settings.py
  docker-app/qfieldcloud/subscription/exceptions.py
  docker-app/qfieldcloud/subscription/tests/test_organization.py
Labels: patch, chore

#643 Workaround vector layer type rename in QGIS 3.30
  docker-app/qfieldcloud/core/models.py
Labels: bug, patch

#641 Remove milliseconds from `active_since` and `active_until` respectively
  docker-app/qfieldcloud/subscription/models.py
Labels: bug, patch

#648 Fix flaky subscription test due to microseconds overlaps
  docker-app/qfieldcloud/subscription/tests/test_subscription.py
Labels: bug, patch

#646 Speed up delta_apply jobs by using an indexed column for searching
  docker-app/qfieldcloud/core/migrations/0066_delta_client_id.py
  docker-app/qfieldcloud/core/models.py
  docker-app/qfieldcloud/core/tests/test_admin.py
  docker-app/qfieldcloud/core/tests/test_organization.py
  docker-app/qfieldcloud/core/views/deltas_views.py
  docker-app/worker_wrapper/wrapper.py
Labels: bug, patch

#651 Avoid counting, use qs.exists() instead
  docker-app/qfieldcloud/core/models.py
  docker-app/qfieldcloud/core/permissions_utils.py
  docker-app/qfieldcloud/core/tests/test_packages.py
  docker-app/qfieldcloud/core/utils2/jobs.py
  docker-app/qfieldcloud/core/views/files_views.py
  docker-app/qfieldcloud/subscription/models.py
Labels: minor, chore

#654 A bit more type safety here and there
  docker-app/qfieldcloud/settings.py
  docker-qgis/apply_deltas.py
Labels: patch, chore

#650 Always accept file uploads from Qfield
  docker-app/qfieldcloud/core/models.py
  docker-app/qfieldcloud/core/permissions_utils.py
  docker-app/qfieldcloud/core/tests/test_file_upload_policy.py
  docker-app/qfieldcloud/core/tests/test_job.py
  docker-app/qfieldcloud/core/tests/test_packages.py
  docker-app/qfieldcloud/core/tests/utils.py
  docker-app/qfieldcloud/core/views/files_views.py
  docker-app/qfieldcloud/core/views/qfield_files_views.py
Labels: bug, patch

#656 A bit of 484
  docker-app/qfieldcloud/core/models.py
  docker-app/worker_wrapper/wrapper.py
Labels: patch, chore

#658 Simplify query for busy projects in dequeue.py
  docker-app/qfieldcloud/core/management/commands/dequeue.py
Labels: minor, chore

#664 Be more strict when updating jobs, set `update_fields` on each `.save()`
  docker-app/qfieldcloud/core/management/commands/dequeue.py
  docker-app/worker_wrapper/wrapper.py
Labels: patch, refactor

#659 Use project.jobs instead of Jobs.filter(project=project)
  docker-app/qfieldcloud/core/models.py
  docker-app/qfieldcloud/core/tests/utils.py
Labels: minor, chore

#653 Some small improvements on type safety side
  docker-app/qfieldcloud/core/utils2/jobs.py
  docker-qgis/utils.py
Labels: patch, chore

#652 [chore] Add and apply `pyupgrade` to `pre-commit`
  .pre-commit-config.yaml
  docker-app/qfieldcloud/authentication/tests/test_authentication.py
  docker-app/qfieldcloud/authentication/views.py
  docker-app/qfieldcloud/core/admin.py
  docker-app/qfieldcloud/core/geodb_utils.py
  docker-app/qfieldcloud/core/management/commands/status.py
  docker-app/qfieldcloud/core/models.py
  docker-app/qfieldcloud/core/serializers.py
  docker-app/qfieldcloud/core/tests/test_deleteorphanedfiles.py
  docker-app/qfieldcloud/core/tests/test_delta.py
  docker-app/qfieldcloud/core/tests/test_packages.py
  docker-app/qfieldcloud/core/tests/test_permission.py
  docker-app/qfieldcloud/core/tests/test_project.py
  docker-app/qfieldcloud/core/tests/test_qfield_file.py
  docker-app/qfieldcloud/core/tests/test_qgis_file.py
  docker-app/qfieldcloud/core/tests/test_user.py
  docker-app/qfieldcloud/core/utils.py
  docker-app/qfieldcloud/core/utils2/storage.py
  docker-app/qfieldcloud/core/views/files_views.py
  docker-app/qfieldcloud/subscription/tests/test_external_db.py
  docker-app/qfieldcloud/subscription/tests/test_package.py
  docker-app/worker_wrapper/wrapper.py
  docker-qgis/apply_deltas.py
  docker-qgis/tests/test_qgis.py
  scripts/check_envvars.py
Labels: patch, chore

#663 Some type updates in core app
  docker-app/qfieldcloud/core/admin.py
  docker-app/qfieldcloud/core/querysets_utils.py
  docker-app/qfieldcloud/core/serializers.py
  docker-app/qfieldcloud/subscription/models.py
Labels: patch, chore

#660 Cancel jobs on project delete
  docker-app/qfieldcloud/core/management/commands/dequeue.py
  docker-app/qfieldcloud/core/migrations/0068_job_container_id.py
  docker-app/qfieldcloud/core/models.py
  docker-app/worker_wrapper/wrapper.py
Labels: enhancement, minor

#666 Bump various deps
  docker-app/qfieldcloud/notifs/tests/test_notifs.py
  docker-app/requirements.txt
Labels: enhancement, patch
