Repository opengisch/QFieldCloud, pull requests merged in 2023-03, with the labels that each got.

#537 Added django-extensions dependency to make life sweet
  docker-app/Dockerfile
  docker-app/qfieldcloud/settings.py
  docker-app/requirements.txt
Labels: enhancement, patch

#538 Add some admin improvements
  docker-app/qfieldcloud/core/admin.py
  docker-app/qfieldcloud/subscription/models.py
  docker-app/qfieldcloud/subscription/tests/test_package.py
  docker-app/requirements.txt
Labels: enhancement, patch

#539 Speed up delta admin by adding some indices
  docker-app/qfieldcloud/core/migrations/0063_auto_20230305_1551.py
  docker-app/qfieldcloud/core/models.py
Labels: enhancement, patch

#542 Ignore certbot created files
  .gitignore
Labels: chore

#543 Always use boto3 session when creating different objects.
  docker-app/qfieldcloud/core/utils.py
Labels: bug, patch

#544 Remove the "depends_on" from most of the services, as they are bringi…
  docker-compose.override.dev.yml
  docker-compose.override.local.yml
  docker-compose.yml
Labels: chore

#558 Silent `QuotaError` from Sentry
  docker-app/qfieldcloud/settings.py
Labels: enhancement, patch

#557 Add more logs trying to see what is wrong with file uploads
  docker-app/qfieldcloud/core/views/files_views.py
Labels: chore

#555 No adding version param on api request to download file when no versi…
  docker-app/qfieldcloud/core/templates/admin/project_files_widget.html
Labels: bugfix

#562 Tiny git workflow improvements
  .github/workflows/test.yml
  .gitignore
Labels: chore

#556 QF 2587 human readable sizes in downloadable files
  docker-app/qfieldcloud/core/templates/admin/project_files_widget.html
Labels: enhancement

#576 Forbid usage of match/case in the codebase
  .pre-commit-config.yaml
Labels: chore

#581 Make the root of QFieldCloud redirect to admin page and doc some envvars
  .env.example
  docker-app/qfieldcloud/urls.py
Labels: enhancement, patch

#582 Remove bootstrap submodule as it is no longer needed
  .gitmodules
Labels: enhancement, patch

#573 typo in .env.example
  .env.example
Labels: chore, OK despite flaky test

#588 Fix comparing the deltas with current data for some some datatypes, mostly dates and times
  docker-app/qfieldcloud/core/tests/test_delta.py
  docker-app/qfieldcloud/core/tests/testdata/delta/deltas/special_data_types.json
  docker-app/qfieldcloud/core/tests/testdata/delta/project.qgs
  docker-app/qfieldcloud/core/tests/testdata/delta/testdata.gpkg
  docker-qgis/apply_deltas.py
Labels: bug, patch

#591 Added column showing number of recently active users to projets under `OrganizationAdmin`
  docker-app/qfieldcloud/core/admin.py
Labels: enhancement, false positive from flaky test

#548 Erroneous mimetypes invalidated, not thrown
  docker-app/qfieldcloud/core/utils2/storage.py
Labels: enhancement, false positive from flaky test

#583 Increase dh primes to 4096 bits and load `ssl-dhparams.pem` and `options-ssl-nginx.conf` configs
  conf/nginx/ssl-dhparams.pem
  conf/nginx/templates/default.conf.template
Labels: enhancement, patch

#595 Changed the DH param
  conf/nginx/ssl-dhparams.pem
Labels: chore

#596 Prefer importing the `storage` module over using the full module path
  docker-app/qfieldcloud/core/models.py
  docker-app/worker_wrapper/wrapper.py
Labels: chore

#594 Configure locales and languages
  docker-app/Dockerfile
  docker-app/qfieldcloud/settings.py
Labels: enhancement, patch

#597 Set USE_I18N=False to prevent semi-translated UI
  docker-app/qfieldcloud/settings.py
Labels: bug, patch

#601 Reduce the default Django list per page from 100 to 20 items
  docker-app/qfieldcloud/core/admin.py
  docker-app/qfieldcloud/settings.py
Labels: enhancement, patch

#600 Improve debugpy documentation and support
  .env.example
  .gitignore
  README.md
  docker-compose.override.local.yml
  docker-compose.override.test.yml
  scripts/check_envvars.sh
Labels: chore

#605 Add provider name to get more detailed layer information
  docker-qgis/utils.py
Labels: enhancement, patch

#607 Added project status in the admin
  docker-app/qfieldcloud/core/admin.py
Labels: enhancement, patch
