Repository opengisch/QFieldCloud, pull requests merged in 2023-08, with the labels that each got.

#739 Django command for extracting S3 version files metadata
  docker-app/qfieldcloud/core/management/commands/extracts3data.py
  docker-app/qfieldcloud/core/tests/test_commands.py
  docker-app/qfieldcloud/core/utils.py
Labels: enhancement

#757 Make OpenAPI docs more up to date, document wrong and hidden request and response params
  docker-app/qfieldcloud/core/pagination.py
  docker-app/qfieldcloud/core/serializers.py
  docker-app/qfieldcloud/core/views/deltas_views.py
  docker-app/qfieldcloud/core/views/files_views.py
  docker-app/qfieldcloud/core/views/jobs_views.py
  docker-app/qfieldcloud/core/views/package_views.py
  docker-app/qfieldcloud/core/views/projects_views.py
  docker-app/qfieldcloud/core/views/qfield_files_views.py
Labels: documentation

#766 Bump ci and avoid node 12 deprecation
  .github/workflows/build_and_push.yml
  .github/workflows/test.yml
Labels: chore

#768 Fix settings link in notifications email
  docker-app/qfieldcloud/notifs/cron.py
Labels: bug, patch

#767 Cleanup @deprecated code that affect only tests
  docker-app/qfieldcloud/core/exceptions.py
  docker-app/qfieldcloud/core/models.py
  docker-app/qfieldcloud/core/permissions_utils.py
  docker-app/qfieldcloud/notifs/cron.py
  docker-app/qfieldcloud/subscription/models.py
  docker-app/qfieldcloud/subscription/tests/test_package.py
Labels: minor, chore, refactor

#760 Sending raw body to sentry
  docker-app/qfieldcloud/core/middleware/requests.py
  docker-app/qfieldcloud/core/tests/test_sentry.py
  docker-app/qfieldcloud/core/utils2/sentry.py
  docker-app/qfieldcloud/core/views/files_views.py
  docker-app/qfieldcloud/settings.py
Labels: chore

#773 Cannot add organization owner as collaborator to project
  docker-app/qfieldcloud/core/models.py
Labels: minor

#778 Type hints in worker_wrapper
  docker-app/worker_wrapper/wrapper.py
  docker-qgis/entrypoint.py
Labels: chore
