Repository opengisch/QFieldCloud, pull requests merged in 2023-10, with the labels that each got.

#798 Track remaining_trial_organizations on org owner
  docker-app/qfieldcloud/subscription/models.py
  docker-app/qfieldcloud/subscription/tests/test_subscription.py
Labels: bug, patch

#800 Catching exceptions earlier when trying to cancel orphans containers with empty references
  docker-app/worker_wrapper/wrapper.py
Labels: bug

#782 Improving project file validation user experience
  docker-qgis/process_projectfile.py
  docker-qgis/utils.py
Labels: enhancement, do not merge

#792 Bump QGIS to 3.32.2
  docker-qgis/Dockerfile
Labels: do not merge

#797 Ensure subscription created_by Person and overwrite createsuperuser
  docker-app/qfieldcloud/core/management/commands/createsuperuser.py
  docker-app/qfieldcloud/core/management/commands/createuser.py
  docker-app/qfieldcloud/settings.py
  docker-app/qfieldcloud/subscription/models.py
Labels: bug, patch

#794 Removed redis as a dependency
  .env.example
  .github/workflows/build_and_push.yml
  .pre-commit-config.yaml
  README.md
  docker-app/qfieldcloud/core/management/commands/status.py
  docker-app/qfieldcloud/core/tests/test_api.py
  docker-app/qfieldcloud/core/utils.py
  docker-app/qfieldcloud/core/views/status_views.py
  docker-app/requirements.txt
  docker-app/wait_for_services.py
  docker-compose.override.local.yml
  docker-compose.yml
  docker-redis/Dockerfile
  docker-redis/redis.conf
Labels: chore, do not merge

#793 Bump `qfieldcloud-sdk` dependency
  docker-qgis/requirements.txt
Labels: do not merge
